# Generated by Django 6.0.2 on 2026-02-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='response',
            name='responder',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
